### PR TITLE
feat(ts-typings): add TS type definitions

### PR DESCRIPTION
**Pull request by Hotell**
;) 🍺

### CODE REVIEW

**Comment by treshugart** [comment]
I wonder if it's just worth writing in TypeScript :p. Not much code :)

**Comment by Hotell** [comment]
well I and our team our work writes TS everywhere. Currently I have manually created those defs in `blaze-elements` https://github.com/wc-catalogue/blaze-elements/pull/130/files#diff-db0786508d94338729cb29f68ebd34cf

Anyway this project is very good guinea pig for you to try out TS ;) wdyt?

**Comment by treshugart** [comment]
I'm keen to give it a go.

**Comment by treshugart** [comment]
Merge this at your convenience. I've raised the TS rewrite in #9.

**Comment by Hotell** [comment]
Oh I don't have rights to merge, cause we are not in Skate group :)
Can you merge this pls?

thx

**Comment by treshugart** [comment]
Oh, haha. Sure.

**Pull request merged**
